# Generated by Django 5.1.2 on 2024-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('wallet', 'Wallet'), ('cryptocurrency', 'Cryptocurrency')], max_length=50),
        ),
    ]
