# Generated by Django 5.1.2 on 2024-10-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='num_of_tickets',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='total_price',
        ),
    ]
