# Generated by Django 5.1.2 on 2024-10-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='movies',
            new_name='showtime',
        ),
    ]
