# Generated by Django 5.1.2 on 2024-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_rename_movies_discount_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
