# Generated by Django 5.1.2 on 2024-10-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='showtime',
            field=models.ManyToManyField(blank=True, to='ticket.showtime'),
        ),
    ]
