# Generated by Django 5.1.2 on 2024-10-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_discount_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
