# Generated by Django 5.1.2 on 2024-10-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_discount_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
