# Generated by Django 5.1.2 on 2024-10-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_discount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='active',
        ),
    ]
